[package]
name = "game-search"
version = "2.22.1"
edition = "2021"

[lib]
name = "game_search_lib"
crate-type = ["cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "io-util", "time", "fs", "sync", "rt-multi-thread", "macros", "process"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12"] }
suppaftp = { version = "12", default-features = false, features = ["tokio"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
futures-util = "0.3"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "webp"] }
keyring = { version = "3", features = ["windows-native"] }
uuid = { version = "1", features = ["v4"] }
url = "2"
zip = { version = "2", default-features = false, features = ["deflate"] }
sha2 = "0.10"
regex = "1"
scraper = "0.21"
strsim = "0.11"
unrar = "0.5"

unrar_sys = "=0.5.8"
lz4 = "1"
crc32fast = "1"

[dev-dependencies]
exfat = "0.1"
